// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	DeactivateGroup(ctx context.Context, arg DeactivateGroupParams) error
	DeleteAccount(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetGroup(ctx context.Context, id int64) (Group, error)
	GetGroupForUpdate(ctx context.Context, id int64) (Group, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListGroups(ctx context.Context, arg ListGroupsParams) ([]Group, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
}

var _ Querier = (*Queries)(nil)
